version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    restart: unless-stopped
    platform: linux/amd64
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_PORT=7860
    volumes:
      - ./langflow_data:/data
